### PR TITLE
Add (and fix) formatting for JS and ObjC

### PR DESCRIPTION
**Pull request by ingo**

### CODE REVIEW

**Comment by ingo** [comment]
@dawsontoth @jhaynie Please take a look at this and let me know if it makes sense.

**Comment by dawsontoth** [comment]
npm-debug.log probably shouldn't be included.

**Comment by ingo** [comment]
@dawsontoth how about now? I removed that file and made a few more simplifications.

**Comment by dawsontoth** [comment]
I ran `npm install` followed by `grunt` in the node project, and got this warning:

    > grunt
    >> Local Npm module "grunt-jscs" not found. Is it installed?

So I manually `npm install`ed it, and that warning went away. But when I run grunt, the tests pass, but the coverage fails for an opaque reason:

```
> grunt
Running "appcJs:src" (appcJs) task

Running "jshint:src" (jshint) task
>> 1 file lint free.

Running "jscs:src" (jscs) task
>> 1 files without code style errors.

Running "mochaTest:unit" (mochaTest) task


  library
    ✓ should support sha1 
    ✓ should support generateLargeRandomValue with default size 
    ✓ should support generateLargeRandomValue with different size 
    ✓ should support generateLargeRandomValue with different encoding 
    ✓ should encrypt to base64 (322ms)
    ✓ should encrypt (309ms)
    ✓ should encrypt using AES128 (151ms)
    ✓ should encrypt using AES192 (303ms)
    ✓ should encrypt using AES256 (310ms)
    ✓ should fail to encrypt using invalid size 
    ✓ should not fail to encrypt with short key (153ms)
    ✓ should not fail to encrypt with short pepper (146ms)
    ✓ should not fail to encrypt with short hmac (141ms)
    ✓ should encrypt to hex as default (297ms)
    ✓ should encrypt json string (307ms)
    ✓ should encrypt fail with invalid encoding (155ms)
    ✓ should fail to decrypt with invalid encrypted blob (151ms)
    ✓ should fail to decrypt with wrong key (306ms)
    ✓ should fail to decrypt with wrong pepper (150ms)
    ✓ should fail to decrypt with wrong hmac (153ms)
    ✓ should fail to decrypt with wrong encryption (153ms)
    ✓ should fail to decrypt with modified hmac (150ms)


  22 passing (4s)


Running "kahvesi:src" (kahvesi) task
>> test coverage report generated

Running "coveralls:grunt_coveralls" (coveralls) task
>> Failed to submit 'coverage/lcov.info' to coveralls: Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
>> Failed to submit coverage results to coveralls
Warning: Task "coveralls:grunt_coveralls" failed. Use --force to continue.

Aborted due to warnings.
>
 ```

**Comment by ingo** [comment]
So the first error was my bad. The second seems to be problematic with coveralls on local branches, so I changed it to a warning. My plan is to replace coveralls with a better version. Ethos point the Travis build passed without either of those errors, so I think it's good.

**Pull request merged**
